# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_control(object):
    def setupUi(self, control):
        control.setObjectName("control")
        control.resize(1475, 856)
        self.centralwidget = QtWidgets.QWidget(control)
        self.centralwidget.setObjectName("centralwidget")
        self.label_video = QtWidgets.QLabel(self.centralwidget)
        self.label_video.setGeometry(QtCore.QRect(10, 70, 1280, 720))
        self.label_video.setFrameShape(QtWidgets.QFrame.Box)
        self.label_video.setObjectName("label_video")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1330, 70, 101, 194))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_button1 = QtWidgets.QPushButton(self.layoutWidget)
        self.start_button1.setObjectName("start_button1")
        self.verticalLayout.addWidget(self.start_button1)
        self.start_button2 = QtWidgets.QPushButton(self.layoutWidget)
        self.start_button2.setObjectName("start_button2")
        self.verticalLayout.addWidget(self.start_button2)
        self.start_button3 = QtWidgets.QPushButton(self.layoutWidget)
        self.start_button3.setObjectName("start_button3")
        self.verticalLayout.addWidget(self.start_button3)
        self.start_button4 = QtWidgets.QPushButton(self.layoutWidget)
        self.start_button4.setObjectName("start_button4")
        self.verticalLayout.addWidget(self.start_button4)
        self.start_button_all = QtWidgets.QPushButton(self.layoutWidget)
        self.start_button_all.setObjectName("start_button_all")
        self.verticalLayout.addWidget(self.start_button_all)
        self.stop_button = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout.addWidget(self.stop_button)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(10, 30, 99, 27))
        self.start_button.setObjectName("start_button")
        control.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(control)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1475, 25))
        self.menubar.setObjectName("menubar")
        control.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(control)
        self.statusbar.setObjectName("statusbar")
        control.setStatusBar(self.statusbar)

        self.retranslateUi(control)
        QtCore.QMetaObject.connectSlotsByName(control)

    def retranslateUi(self, control):
        _translate = QtCore.QCoreApplication.translate
        control.setWindowTitle(_translate("control", "MainWindow"))
        self.label_video.setText(_translate("control", "video_feed"))
        self.start_button1.setText(_translate("control", "Start 1"))
        self.start_button2.setText(_translate("control", "Start 2"))
        self.start_button3.setText(_translate("control", "Start 3"))
        self.start_button4.setText(_translate("control", "Start 4"))
        self.start_button_all.setText(_translate("control", "Start all"))
        self.stop_button.setText(_translate("control", "STOP ALL"))
        self.start_button.setText(_translate("control", "Start Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    control = QtWidgets.QMainWindow()
    ui = Ui_control()
    ui.setupUi(control)
    control.show()
    sys.exit(app.exec_())
