# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygame_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pygame_test(object):
    def setupUi(self, pygame_test):
        pygame_test.setObjectName("pygame_test")
        pygame_test.resize(921, 611)
        self.centralwidget = QtWidgets.QWidget(pygame_test)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 20, 171, 16))
        self.label.setObjectName("label")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(800, 30, 99, 27))
        self.start_button.setObjectName("start_button")
        pygame_test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pygame_test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 25))
        self.menubar.setObjectName("menubar")
        pygame_test.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pygame_test)
        self.statusbar.setObjectName("statusbar")
        pygame_test.setStatusBar(self.statusbar)

        self.retranslateUi(pygame_test)
        QtCore.QMetaObject.connectSlotsByName(pygame_test)

    def retranslateUi(self, pygame_test):
        _translate = QtCore.QCoreApplication.translate
        pygame_test.setWindowTitle(_translate("pygame_test", "MainWindow"))
        self.label.setText(_translate("pygame_test", "pygame test"))
        self.start_button.setText(_translate("pygame_test", "start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pygame_test = QtWidgets.QMainWindow()
    ui = Ui_pygame_test()
    ui.setupUi(pygame_test)
    pygame_test.show()
    sys.exit(app.exec_())
