# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'path_planner.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_path_planner(object):
    def setupUi(self, path_planner):
        path_planner.setObjectName("path_planner")
        path_planner.resize(1348, 985)
        self.centralwidget = QtWidgets.QWidget(path_planner)
        self.centralwidget.setObjectName("centralwidget")
        self.label_video = QtWidgets.QLabel(self.centralwidget)
        self.label_video.setGeometry(QtCore.QRect(10, 210, 1280, 720))
        self.label_video.setFrameShape(QtWidgets.QFrame.Box)
        self.label_video.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_video.setLineWidth(3)
        self.label_video.setObjectName("label_video")
        self.code_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.code_edit.setGeometry(QtCore.QRect(1140, 170, 141, 27))
        self.code_edit.setObjectName("code_edit")
        self.routes_button = QtWidgets.QPushButton(self.centralwidget)
        self.routes_button.setGeometry(QtCore.QRect(1148, 140, 121, 27))
        self.routes_button.setObjectName("routes_button")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(10, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.checkBox_start = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_start.setGeometry(QtCore.QRect(546, 130, 221, 22))
        self.checkBox_start.setObjectName("checkBox_start")
        self.checkBox_finish = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_finish.setGeometry(QtCore.QRect(550, 170, 221, 22))
        self.checkBox_finish.setObjectName("checkBox_finish")
        self.edit_x_start = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_x_start.setGeometry(QtCore.QRect(790, 130, 111, 31))
        self.edit_x_start.setObjectName("edit_x_start")
        self.edit_y_start = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_y_start.setGeometry(QtCore.QRect(920, 130, 111, 31))
        self.edit_y_start.setObjectName("edit_y_start")
        self.edit_x_finish = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_x_finish.setGeometry(QtCore.QRect(790, 170, 111, 31))
        self.edit_x_finish.setObjectName("edit_x_finish")
        self.edit_y_finish = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_y_finish.setGeometry(QtCore.QRect(920, 170, 111, 31))
        self.edit_y_finish.setObjectName("edit_y_finish")
        self.edit_y_now = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_y_now.setGeometry(QtCore.QRect(130, 890, 111, 31))
        self.edit_y_now.setObjectName("edit_y_now")
        self.edit_x_now = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_x_now.setGeometry(QtCore.QRect(20, 890, 111, 31))
        self.edit_x_now.setObjectName("edit_x_now")
        path_planner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(path_planner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1348, 25))
        self.menubar.setObjectName("menubar")
        self.menuPath_Planner_RRT = QtWidgets.QMenu(self.menubar)
        self.menuPath_Planner_RRT.setObjectName("menuPath_Planner_RRT")
        path_planner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(path_planner)
        self.statusbar.setObjectName("statusbar")
        path_planner.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPath_Planner_RRT.menuAction())

        self.retranslateUi(path_planner)
        QtCore.QMetaObject.connectSlotsByName(path_planner)

    def retranslateUi(self, path_planner):
        _translate = QtCore.QCoreApplication.translate
        path_planner.setWindowTitle(_translate("path_planner", "MainWindow"))
        self.label_video.setText(_translate("path_planner", "video_feed"))
        self.routes_button.setText(_translate("path_planner", "Calculate route"))
        self.start_button.setText(_translate("path_planner", "Start video"))
        self.checkBox_start.setText(_translate("path_planner", "Seleccionar punto de partida"))
        self.checkBox_finish.setText(_translate("path_planner", "Seleccionar punto de llegada"))
        self.menuPath_Planner_RRT.setTitle(_translate("path_planner", "Path Planner RRT*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    path_planner = QtWidgets.QMainWindow()
    ui = Ui_path_planner()
    ui.setupUi(path_planner)
    path_planner.show()
    sys.exit(app.exec_())
